apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: test-object-detection-secret-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-object-detection-secret-3
    app.kubernetes.io/part-of: test-object-detection-secret-3  
  name: test-object-detection-secret-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-object-detection-secret-3 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-object-detection-secret-3
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: test-object-detection-secret-3-model-config
        env:
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: model-service-secret
              key: MODEL_SERVICE_SECRET2
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
